controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    controller: App\Controller\MobileAuthController::login
    methods: ['POST']

api_register:
    path: /api/register
    controller: App\Controller\MobileAuthController::register
    methods: ['POST']

# Routes pour l'API mobile
api_mobile_login:
    path: /api/mobile/login_check
    controller: App\Controller\MobileAuthController::login
    methods: ['POST']

api_mobile_register:
    path: /api/mobile/register
    controller: App\Controller\MobileAuthController::register
    methods: ['POST']

api_mobile_test:
    path: /api/mobile/test
    controller: App\Controller\MobileAuthController::test
    methods: ['GET']

api_mobile_user:
    path: /api/mobile/user
    controller: App\Controller\MobileAuthController::userProfile
    methods: ['GET'] 